using Site.lib.ViewModels;

namespace Site.lib.Sofan.Seed;

public abstract class SeedAttribute
{
    public static VmInitialProperty Root => new() {PropId = 0,ParentId = 0,PropArName = "Root",PropEnName = "Root",Order = 0};
    public static VmInitialProperty Security => new() {PropId = 1,ParentId = 0,PropArName = "Security",PropEnName = "Security",Order = 0};
    public static VmInitialProperty Static => new() {PropId = 2,ParentId = 0,PropArName = "Static",PropEnName = "Static",Order = 0};
    public static VmInitialProperty EntryTypes => new() {PropId = 3,ParentId = 0,PropArName = "Domains",PropEnName = "Domains",Order = 0};
    public static VmInitialProperty Types => new() {PropId = 5,ParentId = 0,PropArName = "Types",PropEnName = "Types",Order = 0};
}

public class SeedSecurity
{
    private static readonly long BaseId = SeedAttribute.Security.PropId;
    public static VmInitialProperty Users => new() {PropId = (BaseId*100)+1,ParentId = BaseId,PropArName = "Users",PropEnName = "Users",Order = 1};
    public static VmInitialProperty Roles => new() {PropId = (BaseId*100)+2,ParentId = BaseId,PropArName = "Roles",PropEnName = "Roles",Order = 2};
    public static VmInitialProperty Permissions => new() {PropId = (BaseId*100)+3,ParentId = BaseId,PropArName = "Permissions",PropEnName = "Permissions",Order = 3};
}

public class SeedEntryTypes
{
    private static readonly long BaseId = SeedAttribute.EntryTypes.PropId;
    public static VmInitialProperty Department => new() {PropId = (BaseId*100)+1,ParentId = BaseId,PropArName = "Department",PropEnName = "Department",Order = 1};
    public static VmInitialProperty Page => new() {PropId = (BaseId*100)+2,ParentId = BaseId,PropArName = "Page",PropEnName = "Page",Order = 1};
    public static VmInitialProperty Slider => new() {PropId = (BaseId*100)+3,ParentId = BaseId,PropArName = "Slider",PropEnName = "Slider",Order = 1};
    public static VmInitialProperty Section => new() {PropId = (BaseId*100)+4,ParentId = BaseId,PropArName = "Section",PropEnName = "Section",Order = 1};
    public static VmInitialProperty Header => new() {PropId = (BaseId*100)+5,ParentId = BaseId,PropArName = "Header",PropEnName = "Header",Order = 1};
    public static VmInitialProperty Footer => new() {PropId = (BaseId*100)+7,ParentId = BaseId,PropArName = "Footer",PropEnName = "Footer",Order = 1};
}

public class SeedTypes
{
    private static readonly long BaseId = SeedAttribute.Types.PropId;
    public static VmInitialProperty Contact => new() {PropId = (BaseId*100)+1,ParentId = BaseId,PropArName = "Contact",PropEnName = "Contact",Order = 1};
    public static VmInitialProperty Gallery => new() {PropId = (BaseId*100)+2,ParentId = BaseId,PropArName = "Gallery",PropEnName = "Gallery",Order = 1};
    public static VmInitialProperty Image => new() {PropId = (BaseId*100)+3,ParentId = BaseId,PropArName = "Image",PropEnName = "Image",Order = 1};
    public static VmInitialProperty File => new() {PropId = (BaseId*100)+4,ParentId = BaseId,PropArName = "File",PropEnName = "File",Order = 1};
    public static VmInitialProperty Product => new() {PropId = (BaseId*100)+5,ParentId = BaseId,PropArName = "Product",PropEnName = "Product",Order = 1};
    public static VmInitialProperty Branch => new() {PropId = (BaseId*100)+6,ParentId = BaseId,PropArName = "Branch",PropEnName = "Branch",Order = 1};
    public static VmInitialProperty Applicant => new() {PropId = (BaseId*100)+7,ParentId = BaseId,PropArName = "Applicant",PropEnName = "Applicant",Order = 1};
    public static VmInitialProperty Video => new() {PropId = (BaseId*100)+8,ParentId = BaseId,PropArName = "Video",PropEnName = "Video",Order = 1};
    public static VmInitialProperty PlayList => new() {PropId = (BaseId*100)+9,ParentId = BaseId,PropArName = "PlayList",PropEnName = "PlayList",Order = 1};
    public static VmInitialProperty Counter => new() {PropId = (BaseId*100)+10,ParentId = BaseId,PropArName = "Counter",PropEnName = "Counter",Order = 1};
    public static VmInitialProperty Link => new() {PropId = (BaseId*100)+11,ParentId = BaseId,PropArName = "Link",PropEnName = "Link",Order = 1};
    public static VmInitialProperty Request => new() {PropId = (BaseId*100)+12,ParentId = BaseId,PropArName = "Request",PropEnName = "Request",Order = 1};
}

public class SeedContact
{
    private static readonly long BaseId = SeedTypes.Contact.PropId;
    public static VmInitialProperty Email => new() {PropId = (BaseId*100)+1,ParentId = BaseId,PropArName = "Email",PropEnName = "Email",Order = 1};
    public static VmInitialProperty Phone => new() {PropId = (BaseId*100)+2,ParentId = BaseId,PropArName = "Phone",PropEnName = "Phone",Order = 2};
    public static VmInitialProperty WhatsApp => new() {PropId = (BaseId*100)+3,ParentId = BaseId,PropArName = "WhatsApp",PropEnName = "WhatsApp",Order = 3};
    public static VmInitialProperty Address => new() {PropId = (BaseId*100)+4,ParentId = BaseId,PropArName = "Address",PropEnName = "Address",Order = 4};
    public static VmInitialProperty SocialLinks => new() {PropId = (BaseId*100)+5,ParentId = BaseId,PropArName = "Social Links",PropEnName = "Social Links",Order = 5};
}

public class SeedSocialLinks
{
    private static readonly long BaseId = SeedContact.SocialLinks.PropId;
    public static VmInitialProperty FaceBook => new() {PropId = (BaseId*100)+1,ParentId = BaseId,PropArName = "Facebook",PropEnName = "Facebook",Order = 1};
    public static VmInitialProperty Instagram => new() {PropId = (BaseId*100)+2,ParentId = BaseId,PropArName = "Instagram",PropEnName = "Instagram",Order = 1};
    public static VmInitialProperty Twitter => new() {PropId = (BaseId*100)+3,ParentId = BaseId,PropArName = "Twitter",PropEnName = "Twitter",Order = 1};
}

public class SeedStatic
{
    private static readonly long BaseId = SeedAttribute.Static.ParentId; public static VmInitialProperty Days => new() { PropId = (BaseId*100)+1,ParentId=BaseId, PropArName = "Day", PropEnName = "Day"};
    public static VmInitialProperty Months => new() { PropId = (BaseId*100)+2,ParentId=BaseId, PropArName = "Month", PropEnName = "Month"};
    public static VmInitialProperty Countries => new() { PropId = (BaseId*100)+3,ParentId=BaseId, PropArName = "Countries", PropEnName = "Countries"};
    public static VmInitialProperty Activities => new() { PropId = (BaseId*100)+4,ParentId =BaseId, PropArName = "Activities", PropEnName = "Activities" };
    public static VmInitialProperty EntryContentTypes => new() { PropId = (BaseId*100)+5,ParentId =BaseId, PropArName = "Entry Content Types", PropEnName = "Entry Content Types" };
}

public abstract class ConfigCountries
{
    private static readonly long BaseId = SeedStatic.Countries.ParentId; public static VmInitialProperty Afghanistan => new() { PropId = (BaseId*1000)+1,ParentId=BaseId, PropArName = "أفغانستان", PropEnName = "Afghanistan", Misc001 = "man/media/flags/afghanistan.svg", Misc002 = "Afghan", Misc003 = "AF", Misc004 = "أفغانية" };
        public static VmInitialProperty AlandIslands => new() { PropId = (BaseId*1000)+2,ParentId=BaseId, PropArName = "جزر أولاند", PropEnName = "Aland Islands", Misc001 = "man/media/flags/aland-islands.svg", Misc002 = "Aland Islander", Misc003 = "AX", Misc004 = "أولاندية" };
        public static VmInitialProperty Albania => new() { PropId = (BaseId*1000)+3,ParentId=BaseId, PropArName = "ألبانيا", PropEnName = "Albania", Misc001 = "man/media/flags/albania.svg", Misc002 = "Albanian", Misc003 = "AL", Misc004 = "ألبانية" };
        public static VmInitialProperty Algeria => new() { PropId = (BaseId*1000)+4,ParentId=BaseId, PropArName = "الجزائر", PropEnName = "Algeria", Misc001 = "man/media/flags/algeria.svg", Misc002 = "Algerian", Misc003 = "DZ", Misc004 = "جزائرية" };
        public static VmInitialProperty AmericanSamoa => new() { PropId = (BaseId*1000)+5,ParentId=BaseId, PropArName = "ساموا الأمريكية", PropEnName = "American Samoa", Misc001 = "man/media/flags/american-samoa.svg", Misc002 = "American Samoan", Misc003 = "AS", Misc004 = "ساموية أمريكية" };
        public static VmInitialProperty Andorra => new() { PropId = (BaseId*1000)+6,ParentId=BaseId, PropArName = "أندورا", PropEnName = "Andorra", Misc001 = "man/media/flags/andorra.svg", Misc002 = "Andorran", Misc003 = "AD", Misc004 = "أندورية" };
        public static VmInitialProperty Angola => new() { PropId = (BaseId*1000)+7,ParentId=BaseId, PropArName = "أنغولا", PropEnName = "Angola", Misc001 = "man/media/flags/angola.svg", Misc002 = "Angolan", Misc003 = "AO", Misc004 = "أنغولية" };
        public static VmInitialProperty Anguilla => new() { PropId = (BaseId*1000)+8,ParentId=BaseId, PropArName = "أنغيلا", PropEnName = "Anguilla", Misc001 = "man/media/flags/anguilla.svg", Misc002 = "Anguillan", Misc003 = "AI", Misc004 = "أنغيلا" };
        public static VmInitialProperty AntiguaAndBarbuda => new() { PropId = (BaseId*1000)+9,ParentId=BaseId, PropArName = "أنتيغوا وبربودا", PropEnName = "Antigua and Barbuda", Misc001 = "man/media/flags/antigua-and-barbuda.svg", Misc002 = "Antiguan/Barbudan", Misc003 = "AG", Misc004 = "بربودية" };
        public static VmInitialProperty Argentina => new() { PropId = (BaseId*1000)+10,ParentId=BaseId, PropArName = "الأرجنتين", PropEnName = "Argentina", Misc001 = "man/media/flags/argentina.svg", Misc002 = "Argentine", Misc003 = "AR", Misc004 = "أرجنتينية" };
        public static VmInitialProperty Armenia => new() { PropId = (BaseId*1000)+11,ParentId=BaseId, PropArName = "أرمينيا", PropEnName = "Armenia", Misc001 = "man/media/flags/armenia.svg", Misc002 = "أرميني", Misc003 = "AM"};
        public static VmInitialProperty Aruba => new() { PropId = (BaseId*1000)+12,ParentId=BaseId, PropArName = "أروبا", PropEnName = "Aruba", Misc001 = "man/media/flags/aruba.svg", Misc002 = "أروبي", Misc003 = "AW"};
        public static VmInitialProperty Australia => new() { PropId = (BaseId*1000)+13,ParentId=BaseId, PropArName = "أستراليا", PropEnName = "Australia", Misc001 = "man/media/flags/australia.svg", Misc002 = "أسترالي", Misc003 = "AU"};
        public static VmInitialProperty Austria => new() { PropId = (BaseId*1000)+14,ParentId=BaseId, PropArName = "النمسا", PropEnName = "Austria", Misc001 = "man/media/flags/austria.svg", Misc002 = "نمساوي", Misc003 = "AT"};
        public static VmInitialProperty Azerbaijan => new() { PropId = (BaseId*1000)+15,ParentId=BaseId, PropArName = "أذربيجان", PropEnName = "Azerbaijan", Misc001 = "man/media/flags/azerbaijan.svg", Misc002 = "أذربيجاني", Misc003 = "AZ"};
        public static VmInitialProperty Bahamas => new() { PropId = (BaseId*1000)+16,ParentId=BaseId, PropArName = "جزر البهاما", PropEnName = "Bahamas", Misc001 = "man/media/flags/bahamas.svg", Misc002 = "باهامي", Misc003 = "BS"};
        public static VmInitialProperty Bahrain => new() { PropId = (BaseId*1000)+17,ParentId=BaseId, PropArName = "البحرين", PropEnName = "Bahrain", Misc001 = "man/media/flags/bahrain.svg", Misc002 = "بحريني", Misc003 = "BH"};
        public static VmInitialProperty Bangladesh => new() { PropId = (BaseId*1000)+18,ParentId=BaseId, PropArName = "بنغلاديش", PropEnName = "Bangladesh", Misc001 = "man/media/flags/bangladesh.svg", Misc002 = "بنغلاديشي", Misc003 = "BD"};
        public static VmInitialProperty Barbados => new() { PropId = (BaseId*1000)+19,ParentId=BaseId, PropArName = "بربادوس", PropEnName = "Barbados", Misc001 = "man/media/flags/barbados.svg", Misc002 = "بربادوسي", Misc003 = "BB"};
        public static VmInitialProperty Belarus => new() { PropId = (BaseId*1000)+20,ParentId=BaseId, PropArName = "بيلاروسيا", PropEnName = "Belarus", Misc001 = "man/media/flags/belarus.svg", Misc002 = "بيلاروسي", Misc003 = "BY"};
        public static VmInitialProperty Belgium => new() { PropId = (BaseId*1000)+21,ParentId=BaseId, PropArName = "بلجيكا", PropEnName = "Belgium", Misc001 = "man/media/flags/belgium.svg", Misc002 = "بلجيكي", Misc003 = "BE"};
        public static VmInitialProperty Belize => new() { PropId = (BaseId*1000)+22,ParentId=BaseId, PropArName = "بليز", PropEnName = "Belize", Misc001 = "man/media/flags/belize.svg", Misc002 = "بليزي", Misc003 = "BZ"};
        public static VmInitialProperty Mexico => new() { PropId = (BaseId*1000)+23,ParentId=BaseId, PropArName = "المكسيك", PropEnName = "Mexico", Misc001 = "man/media/flags/mexico.svg", Misc002 = "مكسيكي", Misc003 = "MX"};
        public static VmInitialProperty Benin => new() { PropId = (BaseId*1000)+24,ParentId=BaseId, PropArName = "بنين", PropEnName = "Benin", Misc001 = "man/media/flags/benin.svg", Misc002 = "بنيني", Misc003 = "BJ"};
        public static VmInitialProperty Bermuda => new() { PropId = (BaseId*1000)+25,ParentId=BaseId, PropArName = "برمودا", PropEnName = "Bermuda", Misc001 = "man/media/flags/bermuda.svg", Misc002 = "برمودي", Misc003 = "BM"};
        public static VmInitialProperty Bhutan => new() { PropId = (BaseId*1000)+26,ParentId=BaseId, PropArName = "بوتان", PropEnName = "Bhutan", Misc001 = "man/media/flags/bhutan.svg", Misc002 = "بوتاني", Misc003 = "BT"};
        public static VmInitialProperty Bolivia => new() { PropId = (BaseId*1000)+27,ParentId=BaseId, PropArName = "بوليفيا", PropEnName = "Bolivia, Plurinational State of", Misc001 = "man/media/flags/bolivia.svg", Misc002 = "بوليفي", Misc003 = "BO"};
        public static VmInitialProperty Bonaire => new() { PropId = (BaseId*1000)+28,ParentId=BaseId, PropArName = "بونير", PropEnName = "Bonaire, Sint Eustatius and Saba", Misc001 = "man/media/flags/bonaire.svg", Misc002 = "هولندي", Misc003 = "BQ"};
        public static VmInitialProperty Bosnia => new() { PropId = (BaseId*1000)+29,ParentId=BaseId, PropArName = "البوسنة والهرسك", PropEnName = "Bosnia and Herzegovina", Misc001 = "man/media/flags/bosnia-and-herzegovina.svg", Misc002 = "بوسني/هرسكي", Misc003 = "BA"};
        public static VmInitialProperty Botswana => new() { PropId = (BaseId*1000)+30,ParentId=BaseId, PropArName = "بوتسوانا", PropEnName = "Botswana", Misc001 = "man/media/flags/botswana.svg", Misc002 = "بوتسواني", Misc003 = "BW"};
        public static VmInitialProperty Brazil => new() { PropId = (BaseId*1000)+31,ParentId=BaseId, PropArName = "البرازيل", PropEnName = "Brazil", Misc001 = "man/media/flags/brazil.svg", Misc002 = "برازيلي", Misc003 = "BR"};
        public static VmInitialProperty BritishIndianOceanTerritory => new() { PropId = (BaseId*1000)+32,ParentId=BaseId, PropArName = "إقليم المحيط الهندي البريطاني", PropEnName = "British Indian Ocean Territory", Misc001 = "man/media/flags/british-indian-ocean-territory.svg", Misc002 = "BIOT", Misc003 = "IO"};
        public static VmInitialProperty Brunei => new() { PropId = (BaseId*1000)+33,ParentId=BaseId, PropArName = "بروناي دار السلام", PropEnName = "Brunei Darussalam", Misc001 = "man/media/flags/brunei.svg", Misc002 = "بروناي", Misc003 = "BN"};
        public static VmInitialProperty Bulgaria => new() { PropId = (BaseId*1000)+34,ParentId=BaseId, PropArName = "بلغاريا", PropEnName = "Bulgaria", Misc001 = "man/media/flags/bulgaria.svg", Misc002 = "بلغاري", Misc003 = "BG"};
        public static VmInitialProperty BurkinaFaso => new() { PropId = (BaseId*1000)+35,ParentId=BaseId, PropArName = "بوركينا فاسو", PropEnName = "Burkina Faso", Misc001 = "man/media/flags/burkina-faso.svg", Misc002 = "بوركيني", Misc003 = "BF"};
        public static VmInitialProperty Burundi => new() { PropId = (BaseId*1000)+36,ParentId=BaseId, PropArName = "بوروندي", PropEnName = "Burundi", Misc001 = "man/media/flags/burundi.svg", Misc002 = "بوروندي", Misc003 = "BI"};
        public static VmInitialProperty Cambodia => new() { PropId = (BaseId*1000)+37,ParentId=BaseId, PropArName = "كمبوديا", PropEnName = "Cambodia", Misc001 = "man/media/flags/cambodia.svg", Misc002 = "كمبودي", Misc003 = "KH"};
        public static VmInitialProperty Cameroon => new() { PropId = (BaseId*1000)+38,ParentId=BaseId, PropArName = "الكاميرون", PropEnName = "Cameroon", Misc001 = "man/media/flags/cameroon.svg", Misc002 = "كاميروني", Misc003 = "CM"};
        public static VmInitialProperty Canada => new() { PropId = (BaseId*1000)+39,ParentId=BaseId, PropArName = "كندا", PropEnName = "Canada", Misc001 = "man/media/flags/canada.svg", Misc002 = "كندي", Misc003 = "CA"};
        public static VmInitialProperty CapeVerde => new() { PropId = (BaseId*1000)+40,ParentId=BaseId, PropArName = "الرأس الأخضر", PropEnName = "Cape Verde", Misc001 = "man/media/flags/cape-verde.svg", Misc002 = "الرأس الأخضري", Misc003 = "CV"};
        public static VmInitialProperty CaymanIslands => new() { PropId = (BaseId*1000)+41,ParentId=BaseId, PropArName = "جزر كايمان", PropEnName = "Cayman Islands", Misc001 = "man/media/flags/cayman-islands.svg", Misc002 = "كايماني", Misc003 = "KY"};
        public static VmInitialProperty CentralAfricanRepublic => new() { PropId = (BaseId*1000)+42,ParentId=BaseId, PropArName = "جمهورية أفريقيا الوسطى", PropEnName = "Central African Republic", Misc001 = "man/media/flags/central-african-republic.svg", Misc002 = "أفريقي", Misc003 = "CF"};
        public static VmInitialProperty Chad => new() { PropId = (BaseId*1000)+43,ParentId=BaseId, PropArName = "تشاد", PropEnName = "Chad", Misc001 = "man/media/flags/chad.svg", Misc002 = "تشادي", Misc003 = "TD"};
        public static VmInitialProperty Chile => new() { PropId = (BaseId*1000)+44,ParentId=BaseId, PropArName = "تشيلي", PropEnName = "Chile", Misc001 = "man/media/flags/chile.svg", Misc002 = "تشيلي", Misc003 = "CL"};
        public static VmInitialProperty China => new() { PropId = (BaseId*1000)+45,ParentId=BaseId, PropArName = "الصين", PropEnName = "China", Misc001 = "man/media/flags/china.svg", Misc002 = "صيني", Misc003 = "CN"};
        public static VmInitialProperty ChristmasIsland => new() { PropId = (BaseId*1000)+46,ParentId=BaseId, PropArName = "جزيرة الكريسماس", PropEnName = "Christmas Island", Misc001 = "man/media/flags/christmas-island.svg", Misc002 = "جزيرة الكريسماس", Misc003 = "CX"};
        public static VmInitialProperty CocosIslands => new() { PropId = (BaseId*1000)+47,ParentId=BaseId, PropArName = "جزر كوكوس (كيلينغ)", PropEnName = "Cocos (Keeling) Islands", Misc001 = "man/media/flags/cocos-island.svg", Misc002 = "كوكوس", Misc003 = "CC"};
        public static VmInitialProperty Colombia => new() { PropId = (BaseId*1000)+48,ParentId=BaseId, PropArName = "كولومبيا", PropEnName = "Colombia", Misc001 = "man/media/flags/colombia.svg", Misc002 = "كولومبي", Misc003 = "CO"};
        public static VmInitialProperty Comoros => new() { PropId = (BaseId*1000)+49,ParentId=BaseId, PropArName = "جزر القمر", PropEnName = "Comoros", Misc001 = "man/media/flags/comoros.svg", Misc002 = "قمري", Misc003 = "KM"};
        public static VmInitialProperty CookIslands => new() { PropId = (BaseId*1000)+50,ParentId=BaseId, PropArName = "جزر كوك", PropEnName = "Cook Islands", Misc001 = "man/media/flags/cook-islands.svg", Misc002 = "كوكي", Misc003 = "CK"};
        public static VmInitialProperty CostaRica => new() { PropId = (BaseId*1000)+51,ParentId=BaseId, PropArName = "كوستاريكا", PropEnName = "Costa Rica", Misc001 = "man/media/flags/costa-rica.svg", Misc002 = "كوستاريكي", Misc003 = "CR"};
        public static VmInitialProperty CoteDIvoire => new() { PropId = (BaseId*1000)+52,ParentId=BaseId, PropArName = "كوت ديفوار", PropEnName = "Côte d'Ivoire", Misc001 = "man/media/flags/ivory-coast.svg", Misc002 = "إيفواري", Misc003 = "CI"};
        public static VmInitialProperty Croatia => new() { PropId = (BaseId*1000)+53,ParentId=BaseId, PropArName = "كرواتيا", PropEnName = "Croatia", Misc001 = "man/media/flags/croatia.svg", Misc002 = "كرواتي", Misc003 = "HR"};
        public static VmInitialProperty Cuba => new() { PropId = (BaseId*1000)+54,ParentId=BaseId, PropArName = "كوبا", PropEnName = "Cuba", Misc001 = "man/media/flags/cuba.svg", Misc002 = "كوبي", Misc003 = "CU"};
        public static VmInitialProperty Curacao => new() { PropId = (BaseId*1000)+55,ParentId=BaseId, PropArName = "كوراساو", PropEnName = "Curaçao", Misc001 = "man/media/flags/curacao.svg", Misc002 = "كوراساوي", Misc003 = "CW"};
        public static VmInitialProperty CzechRepublic => new() { PropId = (BaseId*1000)+56,ParentId=BaseId, PropArName = "جمهورية التشيك", PropEnName = "Czech Republic", Misc001 = "man/media/flags/czech-republic.svg", Misc002 = "تشيكي", Misc003 = "CZ"};
        public static VmInitialProperty Denmark => new() { PropId = (BaseId*1000)+57,ParentId=BaseId, PropArName = "الدنمارك", PropEnName = "Denmark", Misc001 = "man/media/flags/denmark.svg", Misc002 = "دنماركي", Misc003 = "DK"};
        public static VmInitialProperty Djibouti => new() { PropId = (BaseId*1000)+58,ParentId=BaseId, PropArName = "جيبوتي", PropEnName = "Djibouti", Misc001 = "man/media/flags/djibouti.svg", Misc002 = "جيبوتي", Misc003 = "DJ"};
        public static VmInitialProperty Dominica => new() { PropId = (BaseId*1000)+59,ParentId=BaseId, PropArName = "دومينيكا", PropEnName = "Dominica", Misc001 = "man/media/flags/dominica.svg", Misc002 = "دومينيكي", Misc003 = "DM"};
        public static VmInitialProperty DominicanRepublic => new() { PropId = (BaseId*1000)+60,ParentId=BaseId, PropArName = "جمهورية الدومينيكان", PropEnName = "Dominican Republic", Misc001 = "man/media/flags/dominican-republic.svg", Misc002 = "دومينيكي", Misc003 = "DO"};
        public static VmInitialProperty Ecuador => new() { PropId = (BaseId*1000)+61,ParentId=BaseId, PropArName = "إكوادور", PropEnName = "Ecuador", Misc001 = "man/media/flags/ecuador.svg", Misc002 = "إكوادوري", Misc003 = "EC"};
        public static VmInitialProperty Egypt => new() { PropId = (BaseId*1000)+62,ParentId=BaseId, PropArName = "مصر", PropEnName = "Egypt", Misc001 = "man/media/flags/egypt.svg", Misc002 = "مصري", Misc003 = "EG"};
        public static VmInitialProperty ElSalvador => new() { PropId = (BaseId*1000)+63,ParentId=BaseId, PropArName = "السلفادور", PropEnName = "El Salvador", Misc001 = "man/media/flags/el-salvador.svg", Misc002 = "سلفادوري", Misc003 = "SV"};
        public static VmInitialProperty EquatorialGuinea => new() { PropId = (BaseId*1000)+64,ParentId=BaseId, PropArName = "غينيا الاستوائية", PropEnName = "Equatorial Guinea", Misc001 = "man/media/flags/equatorial-guinea.svg", Misc002 = "غيني استوائي", Misc003 = "GQ"};
        public static VmInitialProperty Eritrea => new() { PropId = (BaseId*1000)+65,ParentId=BaseId, PropArName = "إريتريا", PropEnName = "Eritrea", Misc001 = "man/media/flags/eritrea.svg", Misc002 = "إريتري", Misc003 = "ER"};
        public static VmInitialProperty Estonia => new() { PropId = (BaseId*1000)+66,ParentId=BaseId, PropArName = "إستونيا", PropEnName = "Estonia", Misc001 = "man/media/flags/estonia.svg", Misc002 = "إستوني", Misc003 = "EE"};
        public static VmInitialProperty Ethiopia => new() { PropId = (BaseId*1000)+67,ParentId=BaseId, PropArName = "إثيوبيا", PropEnName = "Ethiopia", Misc001 = "man/media/flags/ethiopia.svg", Misc002 = "إثيوبي", Misc003 = "ET"};
        public static VmInitialProperty FalklandIslands => new() { PropId = (BaseId*1000)+68,ParentId=BaseId, PropArName = "جزر فوكلاند", PropEnName = "Falkland Islands (Malvinas)", Misc001 = "man/media/flags/falkland-islands.svg", Misc002 = "فوكلاندي", Misc003 = "FK"};
        public static VmInitialProperty Fiji => new() { PropId = (BaseId*1000)+69,ParentId=BaseId, PropArName = "فيجي", PropEnName = "Fiji", Misc001 = "man/media/flags/fiji.svg", Misc002 = "فيجي", Misc003 = "FJ"};
        public static VmInitialProperty Finland => new() { PropId = (BaseId*1000)+70,ParentId=BaseId, PropArName = "فنلندا", PropEnName = "Finland", Misc001 = "man/media/flags/finland.svg", Misc002 = "فنلندي", Misc003 = "FI"};
        public static VmInitialProperty France => new() { PropId = (BaseId*1000)+71,ParentId=BaseId, PropArName = "فرنسا", PropEnName = "France", Misc001 = "man/media/flags/france.svg", Misc002 = "فرنسي", Misc003 = "FR"};
        public static VmInitialProperty FrenchPolynesia => new() { PropId = (BaseId*1000)+72,ParentId=BaseId, PropArName = "بولينيزيا الفرنسية", PropEnName = "French Polynesia", Misc001 = "man/media/flags/french-polynesia.svg", Misc002 = "بولينزي فرنسي", Misc003 = "PF"};
        public static VmInitialProperty Gabon => new() { PropId = (BaseId*1000)+73,ParentId=BaseId, PropArName = "الغابون", PropEnName = "Gabon", Misc001 = "man/media/flags/gabon.svg", Misc002 = "غابوني", Misc003 = "GA"};
        public static VmInitialProperty Gambia => new() { PropId = (BaseId*1000)+74,ParentId=BaseId, PropArName = "غامبيا", PropEnName = "Gambia", Misc001 = "man/media/flags/gambia.svg", Misc002 = "غامبي", Misc003 = "GM"};
        public static VmInitialProperty Georgia => new() { PropId = (BaseId*1000)+75,ParentId=BaseId, PropArName = "جورجيا", PropEnName = "Georgia", Misc001 = "man/media/flags/georgia.svg", Misc002 = "جورجي", Misc003 = "GE"};
        public static VmInitialProperty Germany => new() { PropId = (BaseId*1000)+76,ParentId=BaseId, PropArName = "ألمانيا", PropEnName = "Germany", Misc001 = "man/media/flags/germany.svg", Misc002 = "ألماني", Misc003 = "DE"};
        public static VmInitialProperty Ghana => new() { PropId = (BaseId*1000)+77,ParentId=BaseId, PropArName = "غانا", PropEnName = "Ghana", Misc001 = "man/media/flags/ghana.svg", Misc002 = "غاني", Misc003 = "GH"};
        public static VmInitialProperty Gibraltar => new() { PropId = (BaseId*1000)+78,ParentId=BaseId, PropArName = "جبل طارق", PropEnName = "Gibraltar", Misc001 = "man/media/flags/gibraltar.svg", Misc002 = "جبل طارقي", Misc003 = "GI"};
        public static VmInitialProperty Greece => new() { PropId = (BaseId*1000)+79,ParentId=BaseId, PropArName = "اليونان", PropEnName = "Greece", Misc001 = "man/media/flags/greece.svg", Misc002 = "يوناني", Misc003 = "GR"};
        public static VmInitialProperty Greenland => new() { PropId = (BaseId*1000)+80,ParentId=BaseId, PropArName = "غرينلاند", PropEnName = "Greenland", Misc001 = "man/media/flags/greenland.svg", Misc002 = "غرينلاندي", Misc003 = "GL"};
        public static VmInitialProperty Grenada => new() { PropId = (BaseId*1000)+81,ParentId=BaseId, PropArName = "غرينادا", PropEnName = "Grenada", Misc001 = "man/media/flags/grenada.svg", Misc002 = "غرينادي", Misc003 = "GD"};
        public static VmInitialProperty Guam => new() { PropId = (BaseId*1000)+82,ParentId=BaseId, PropArName = "غوام", PropEnName = "Guam", Misc001 = "man/media/flags/guam.svg", Misc002 = "غوامي", Misc003 = "GU"};
        public static VmInitialProperty Guatemala => new() { PropId = (BaseId*1000)+83,ParentId=BaseId, PropArName = "غواتيمالا", PropEnName = "Guatemala", Misc001 = "man/media/flags/guatemala.svg", Misc002 = "غواتيمالي", Misc003 = "GT"};
        public static VmInitialProperty Guernsey => new() { PropId = (BaseId*1000)+84,ParentId=BaseId, PropArName = "غيرنزي", PropEnName = "Guernsey", Misc001 = "man/media/flags/guernsey.svg", Misc002 = "غيرنزي", Misc003 = "GG"};
        public static VmInitialProperty Guinea => new() { PropId = (BaseId*1000)+85,ParentId=BaseId, PropArName = "غينيا", PropEnName = "Guinea", Misc001 = "man/media/flags/guinea.svg", Misc002 = "غيني", Misc003 = "GN"};
        public static VmInitialProperty GuineaBissau => new() { PropId = (BaseId*1000)+86,ParentId=BaseId, PropArName = "غينيا بيساو", PropEnName = "Guinea-Bissau", Misc001 = "man/media/flags/guinea-bissau.svg", Misc002 = "بيساوي", Misc003 = "GW"};
        public static VmInitialProperty Haiti => new() { PropId = (BaseId*1000)+87,ParentId=BaseId, PropArName = "هايتي", PropEnName = "Haiti", Misc001 = "man/media/flags/haiti.svg", Misc002 = "هايتي", Misc003 = "HT"};
        public static VmInitialProperty VaticanCity => new() { PropId = (BaseId*1000)+88,ParentId=BaseId, PropArName = "مدينة الفاتيكان", PropEnName = "Holy See (Vatican City State)", Misc001 = "man/media/flags/vatican-city.svg", Misc002 = "فاتيكان", Misc003 = "VA"};
        public static VmInitialProperty Honduras => new() { PropId = (BaseId*1000)+89,ParentId=BaseId, PropArName = "هندوراس", PropEnName = "Honduras", Misc001 = "man/media/flags/honduras.svg", Misc002 = "هندوراسي", Misc003 = "HN"};
        public static VmInitialProperty HongKong => new() { PropId = (BaseId*1000)+90,ParentId=BaseId, PropArName = "هونغ كونغ", PropEnName = "Hong Kong", Misc001 = "man/media/flags/hong-kong.svg", Misc002 = "هونغ كونغي", Misc003 = "HK"};
        public static VmInitialProperty Hungary => new() { PropId = (BaseId*1000)+91,ParentId=BaseId, PropArName = "هنغاريا", PropEnName = "Hungary", Misc001 = "man/media/flags/hungary.svg", Misc002 = "Hungarian", Misc003 = "HU", Misc004 = "هنغارية" };
        public static VmInitialProperty Iceland => new() { PropId = (BaseId*1000)+92,ParentId=BaseId, PropArName = "آيسلندا", PropEnName = "Iceland", Misc001 = "man/media/flags/iceland.svg", Misc002 = "Icelandic", Misc003 = "IS", Misc004 = "آيسلندية" };
        public static VmInitialProperty India => new() { PropId = (BaseId*1000)+93,ParentId=BaseId, PropArName = "الهند", PropEnName = "India", Misc001 = "man/media/flags/india.svg", Misc002 = "Indian", Misc003 = "IN", Misc004 = "هندية" };
        public static VmInitialProperty Indonesia => new() { PropId = (BaseId*1000)+94,ParentId=BaseId, PropArName = "إندونيسيا", PropEnName = "Indonesia", Misc001 = "man/media/flags/indonesia.svg", Misc002 = "Indonesian", Misc003 = "ID", Misc004 = "إندونيسية" };
        public static VmInitialProperty Iran => new() { PropId = (BaseId*1000)+95,ParentId=BaseId, PropArName = "إيران", PropEnName = "Iran, Islamic Republic of", Misc001 = "man/media/flags/iran.svg", Misc002 = "Iranian", Misc003 = "IR", Misc004 = "إيرانية" };
        public static VmInitialProperty Iraq => new() { PropId = (BaseId*1000)+96,ParentId=BaseId, PropArName = "العراق", PropEnName = "Iraq", Misc001 = "man/media/flags/iraq.svg", Misc002 = "Iraqi", Misc003 = "IQ", Misc004 = "عراقية" };
        public static VmInitialProperty Ireland => new() { PropId = (BaseId*1000)+97,ParentId=BaseId, PropArName = "أيرلندا", PropEnName = "Ireland", Misc001 = "man/media/flags/ireland.svg", Misc002 = "Irish", Misc003 = "IE", Misc004 = "أيرلندية" };
        public static VmInitialProperty IsleOfMan => new() { PropId = (BaseId*1000)+98,ParentId=BaseId, PropArName = "جزيرة مان", PropEnName = "Isle of Man", Misc001 = "man/media/flags/isle-of-man.svg", Misc002 = "Manx", Misc003 = "IM", Misc004 = "مانكسية" };
        public static VmInitialProperty Italy => new() { PropId = (BaseId*1000)+99,ParentId=BaseId, PropArName = "إيطاليا", PropEnName = "Italy", Misc001 = "man/media/flags/italy.svg", Misc002 = "Italian", Misc003 = "IT", Misc004 = "إيطالية" };
        public static VmInitialProperty Jamaica => new() { PropId = (BaseId*1000)+100,ParentId=BaseId, PropArName = "جامايكا", PropEnName = "Jamaica", Misc001 = "man/media/flags/jamaica.svg", Misc002 = "Jamaican", Misc003 = "JM", Misc004 = "جامايكية" };
        public static VmInitialProperty Japan => new() { PropId = (BaseId*1000)+101,ParentId=BaseId, PropArName = "اليابان", PropEnName = "Japan", Misc001 = "man/media/flags/japan.svg", Misc002 = "Japanese", Misc003 = "JP", Misc004 = "يابانية" };
        public static VmInitialProperty Jersey => new() { PropId = (BaseId*1000)+102,ParentId=BaseId, PropArName = "جيرسي", PropEnName = "Jersey", Misc001 = "man/media/flags/jersey.svg", Misc002 = "Jerseyman", Misc003 = "JE", Misc004 = "جيرزية" };
        public static VmInitialProperty Jordan => new() { PropId = (BaseId*1000)+103,ParentId=BaseId, PropArName = "الأردن", PropEnName = "Jordan", Misc001 = "man/media/flags/jordan.svg", Misc002 = "Jordanian", Misc003 = "JO", Misc004 = "أردنية" };
        public static VmInitialProperty Kazakhstan => new() { PropId = (BaseId*1000)+104,ParentId=BaseId, PropArName = "كازاخستان", PropEnName = "Kazakhstan", Misc001 = "man/media/flags/kazakhstan.svg", Misc002 = "Kazakhstani", Misc003 = "KZ", Misc004 = "كازاخستانية" };
        public static VmInitialProperty Kenya => new() { PropId = (BaseId*1000)+105,ParentId=BaseId, PropArName = "كينيا", PropEnName = "Kenya", Misc001 = "man/media/flags/kenya.svg", Misc002 = "Kenyan", Misc003 = "KE", Misc004 = "كينيا" };
        public static VmInitialProperty Kiribati => new() { PropId = (BaseId*1000)+106,ParentId=BaseId, PropArName = "كيريباتي", PropEnName = "Kiribati", Misc001 = "man/media/flags/kiribati.svg", Misc002 = "I-Kiribati", Misc003 = "KI", Misc004 = "كيريباتية" };
        public static VmInitialProperty NorthKorea => new() { PropId = (BaseId*1000)+107,ParentId=BaseId, PropArName = "كوريا الشمالية", PropEnName = "Korea, Democratic People's Republic of", Misc001 = "man/media/flags/north-korea.svg", Misc002 = "North Korean", Misc003 = "KP", Misc004 = "كورية شمالية" };
        public static VmInitialProperty Kuwait => new() { PropId = (BaseId*1000)+108,ParentId=BaseId, PropArName = "الكويت", PropEnName = "Kuwait", Misc001 = "man/media/flags/kuwait.svg", Misc002 = "Kuwaiti", Misc003 = "KW", Misc004 = "كويتية" };
        public static VmInitialProperty Kyrgyzstan => new() { PropId = (BaseId*1000)+109,ParentId=BaseId, PropArName = "قيرغيزستان", PropEnName = "Kyrgyzstan", Misc001 = "man/media/flags/kyrgyzstan.svg", Misc002 = "Kyrgyzstani", Misc003 = "KG", Misc004 = "قيرغيزستانية" };
        public static VmInitialProperty Laos => new() { PropId = (BaseId*1000)+110,ParentId=BaseId, PropArName = "لاوس", PropEnName = "Lao People's Democratic Republic", Misc001 = "man/media/flags/laos.svg", Misc002 = "Laotian", Misc003 = "LA", Misc004 = "لاوسية" };
        public static VmInitialProperty Latvia => new() { PropId = (BaseId*1000)+111,ParentId=BaseId, PropArName = "لاتفيا", PropEnName = "Latvia", Misc001 = "man/media/flags/latvia.svg", Misc002 = "Latvian", Misc003 = "LV", Misc004 = "لاتفية" };
        public static VmInitialProperty Lebanon => new() { PropId = (BaseId*1000)+112,ParentId=BaseId, PropArName = "لبنان", PropEnName = "Lebanon", Misc001 = "man/media/flags/lebanon.svg", Misc002 = "Lebanese", Misc003 = "LB", Misc004 = "لبنانية" };
        public static VmInitialProperty Lesotho => new() { PropId = (BaseId*1000)+113,ParentId=BaseId, PropArName = "ليسوتو", PropEnName = "Lesotho", Misc001 = "man/media/flags/lesotho.svg", Misc002 = "Basotho", Misc003 = "LS", Misc004 = "ليسوتوية" };
        public static VmInitialProperty Liberia => new() { PropId = (BaseId*1000)+114,ParentId=BaseId, PropArName = "ليبيريا", PropEnName = "Liberia", Misc001 = "man/media/flags/liberia.svg", Misc002 = "Liberian", Misc003 = "LR", Misc004 = "ليبيرية" };
        public static VmInitialProperty Libya => new() { PropId = (BaseId*1000)+115,ParentId=BaseId, PropArName = "ليبيا", PropEnName = "Libya", Misc001 = "man/media/flags/libya.svg", Misc002 = "Libyan", Misc003 = "LY", Misc004 = "ليبية" };
        public static VmInitialProperty Liechtenstein => new() { PropId = (BaseId*1000)+116,ParentId=BaseId, PropArName = "ليختنشتاين", PropEnName = "Liechtenstein", Misc001 = "man/media/flags/liechtenstein.svg", Misc002 = "Liechtenstein", Misc003 = "LI", Misc004 = "ليختنشتاينية" };
        public static VmInitialProperty Lithuania => new() { PropId = (BaseId*1000)+117,ParentId=BaseId, PropArName = "ليتوانيا", PropEnName = "Lithuania", Misc001 = "man/media/flags/lithuania.svg", Misc002 = "Lithuanian", Misc003 = "LT", Misc004 = "ليتوانية" };
        public static VmInitialProperty Luxembourg => new() { PropId = (BaseId*1000)+118,ParentId=BaseId, PropArName = "لوكسمبورغ", PropEnName = "Luxembourg", Misc001 = "man/media/flags/luxembourg.svg", Misc002 = "Luxembourgish", Misc003 = "LU", Misc004 = "لوكسمبورغية" };
        public static VmInitialProperty Macao => new() { PropId = (BaseId*1000)+119,ParentId=BaseId, PropArName = "ماكاو", PropEnName = "Macao", Misc001 = "man/media/flags/macao.svg", Misc002 = "Macanese", Misc003 = "MO", Misc004 = "ماكاوية" };
        public static VmInitialProperty Madagascar => new() { PropId = (BaseId*1000)+120,ParentId=BaseId, PropArName = "مدغشقر", PropEnName = "Madagascar", Misc001 = "man/media/flags/madagascar.svg", Misc002 = "Malagasy", Misc003 = "MG", Misc004 = "مدغشقرية" };
        public static VmInitialProperty Malawi => new() { PropId = (BaseId*1000)+121,ParentId=BaseId, PropArName = "مالاوي", PropEnName = "Malawi", Misc001 = "man/media/flags/malawi.svg", Misc002 = "Malawian", Misc003 = "MW", Misc004 = "مالاوية" };
        public static VmInitialProperty Malaysia => new() { PropId = (BaseId*1000)+122,ParentId=BaseId, PropArName = "ماليزيا", PropEnName = "Malaysia", Misc001 = "man/media/flags/malaysia.svg", Misc002 = "Malaysian", Misc003 = "MY", Misc004 = "ماليزية" };
        public static VmInitialProperty Maldives => new() { PropId = (BaseId*1000)+123,ParentId=BaseId, PropArName = "المالديف", PropEnName = "Maldives", Misc001 = "man/media/flags/maldives.svg", Misc002 = "Maldivian", Misc003 = "MV", Misc004 = "مالديفية" };
        public static VmInitialProperty Mali => new() { PropId = (BaseId*1000)+124,ParentId=BaseId, PropArName = "مالي", PropEnName = "Mali", Misc001 = "man/media/flags/mali.svg", Misc002 = "Malian", Misc003 = "ML", Misc004 = "مالية" };
        public static VmInitialProperty Malta => new() { PropId = (BaseId*1000)+125,ParentId=BaseId, PropArName = "مالطا", PropEnName = "Malta", Misc001 = "man/media/flags/malta.svg", Misc002 = "Maltese", Misc003 = "MT", Misc004 = "مالطية" };
        public static VmInitialProperty MarshallIslands => new() { PropId = (BaseId*1000)+126,ParentId=BaseId, PropArName = "جزر مارشال", PropEnName = "Marshall Islands", Misc001 = "man/media/flags/marshall-island.svg", Misc002 = "Marshallese", Misc003 = "MH", Misc004 = "مارشالية" };
        public static VmInitialProperty Martinique => new() { PropId = (BaseId*1000)+127,ParentId=BaseId, PropArName = "مارتينيك", PropEnName = "Martinique", Misc001 = "man/media/flags/martinique.svg", Misc002 = "Martiniquais", Misc003 = "MQ", Misc004 = "مارتينيكية" };
        public static VmInitialProperty Mauritania => new() { PropId = (BaseId*1000)+128,ParentId=BaseId, PropArName = "موريتانيا", PropEnName = "Mauritania", Misc001 = "man/media/flags/mauritania.svg", Misc002 = "Mauritanian", Misc003 = "MR", Misc004 = "موريتانية" };
        public static VmInitialProperty Mauritius => new() { PropId = (BaseId*1000)+129,ParentId=BaseId, PropArName = "موريشيوس", PropEnName = "Mauritius", Misc001 = "man/media/flags/mauritius.svg", Misc002 = "Mauritian", Misc003 = "MU", Misc004 = "موريشيوسية" };
        public static VmInitialProperty Namibia => new() { PropId = (BaseId*1000)+130,ParentId=BaseId, PropArName = "ناميبيا", PropEnName = "Namibia", Misc001 = "man/media/flags/namibia.svg", Misc002 = "Namibian", Misc003 = "NA", Misc004 = "ناميبية" };
        public static VmInitialProperty Nauru => new() { PropId = (BaseId*1000)+131,ParentId=BaseId, PropArName = "ناورو", PropEnName = "Nauru", Misc001 = "man/media/flags/nauru.svg", Misc002 = "Nauruan", Misc003 = "NR", Misc004 = "ناوروية" };
        public static VmInitialProperty Nepal => new() { PropId = (BaseId*1000)+132,ParentId=BaseId, PropArName = "نيبال", PropEnName = "Nepal", Misc001 = "man/media/flags/nepal.svg", Misc002 = "Nepalese", Misc003 = "NP", Misc004 = "نيبالية" };
        public static VmInitialProperty Netherlands => new() { PropId = (BaseId*1000)+133,ParentId=BaseId, PropArName = "هولندا", PropEnName = "Netherlands", Misc001 = "man/media/flags/netherlands.svg", Misc002 = "Dutch", Misc003 = "NL", Misc004 = "هولندية" };
        public static VmInitialProperty NewZealand => new() { PropId = (BaseId*1000)+134,ParentId=BaseId, PropArName = "نيوزيلندا", PropEnName = "New Zealand", Misc001 = "man/media/flags/new-zealand.svg", Misc002 = "New Zealander", Misc003 = "NZ", Misc004 = "نيوزيلندية" };
        public static VmInitialProperty Nicaragua => new() { PropId = (BaseId*1000)+135,ParentId=BaseId, PropArName = "نيكاراغوا", PropEnName = "Nicaragua", Misc001 = "man/media/flags/nicaragua.svg", Misc002 = "Nicaraguan", Misc003 = "NI", Misc004 = "نيكاراغوية" };
        public static VmInitialProperty Niger => new() { PropId = (BaseId*1000)+136,ParentId=BaseId, PropArName = "النيجر", PropEnName = "Niger", Misc001 = "man/media/flags/niger.svg", Misc002 = "Nigerien", Misc003 = "NE", Misc004 = "نيجرية" };
        public static VmInitialProperty Nigeria => new() { PropId = (BaseId*1000)+137,ParentId=BaseId, PropArName = "نيجيريا", PropEnName = "Nigeria", Misc001 = "man/media/flags/nigeria.svg", Misc002 = "Nigerian", Misc003 = "NG", Misc004 = "نيجيرية" };
        public static VmInitialProperty Niue => new() { PropId = (BaseId*1000)+138,ParentId=BaseId, PropArName = "نيوي", PropEnName = "Niue", Misc001 = "man/media/flags/niue.svg", Misc002 = "Niuean", Misc003 = "NU", Misc004 = "نيوية" };
        public static VmInitialProperty NorfolkIsland => new() { PropId = (BaseId*1000)+139,ParentId=BaseId, PropArName = "جزيرة نورفولك", PropEnName = "Norfolk Island", Misc001 = "man/media/flags/norfolk-island.svg", Misc002 = "Norfolk Islander", Misc003 = "NF", Misc004 = "نورفولكية" };
        public static VmInitialProperty NorthernMarianaIslands => new() { PropId = (BaseId*1000)+140,ParentId=BaseId, PropArName = "جزر ماريانا الشمالية", PropEnName = "Northern Mariana Islands", Misc001 = "man/media/flags/northern-mariana-islands.svg", Misc002 = "Northern Marianan", Misc003 = "MP", Misc004 = "ماريانية شمالية" };
        public static VmInitialProperty Norway => new() { PropId = (BaseId*1000)+141,ParentId=BaseId, PropArName = "النرويج", PropEnName = "Norway", Misc001 = "man/media/flags/norway.svg", Misc002 = "Norwegian", Misc003 = "NO", Misc004 = "نرويجية" };
        public static VmInitialProperty Oman => new() { PropId = (BaseId*1000)+142,ParentId=BaseId, PropArName = "عمان", PropEnName = "Oman", Misc001 = "man/media/flags/oman.svg", Misc002 = "Omani", Misc003 = "OM", Misc004 = "عمانية" };
        public static VmInitialProperty Pakistan => new() { PropId = (BaseId*1000)+143,ParentId=BaseId, PropArName = "باكستان", PropEnName = "Pakistan", Misc001 = "man/media/flags/pakistan.svg", Misc002 = "Pakistani", Misc003 = "PK", Misc004 = "باكستانية" };
        public static VmInitialProperty Palau => new() { PropId = (BaseId*1000)+144,ParentId=BaseId, PropArName = "بالاو", PropEnName = "Palau", Misc001 = "man/media/flags/palau.svg", Misc002 = "Palauan", Misc003 = "PW", Misc004 = "بالاوية" };
        public static VmInitialProperty PalestinianTerritory => new() { PropId = (BaseId*1000)+145,ParentId=BaseId, PropArName = "الأراضي الفلسطينية", PropEnName = "Palestinian Territory, Occupied", Misc001 = "man/media/flags/palestine.svg", Misc002 = "Palestinian", Misc003 = "PS", Misc004 = "فلسطينية" };
        public static VmInitialProperty Panama => new() { PropId = (BaseId*1000)+146,ParentId=BaseId, PropArName = "بنما", PropEnName = "Panama", Misc001 = "man/media/flags/panama.svg", Misc002 = "Panamanian", Misc003 = "PA", Misc004 = "بنمية" };
        public static VmInitialProperty PapuaNewGuinea => new() { PropId = (BaseId*1000)+147,ParentId=BaseId, PropArName = "بابوا غينيا الجديدة", PropEnName = "Papua New Guinea", Misc001 = "man/media/flags/papua-new-guinea.svg", Misc002 = "Papua New Guinean", Misc003 = "PG", Misc004 = "بابوية غينية جديدة" };
        public static VmInitialProperty Paraguay => new() { PropId = (BaseId*1000)+148,ParentId=BaseId, PropArName = "باراغواي", PropEnName = "Paraguay", Misc001 = "man/media/flags/paraguay.svg", Misc002 = "Paraguayan", Misc003 = "PY", Misc004 = "باراغوانية" };
        public static VmInitialProperty Peru => new() { PropId = (BaseId*1000)+149,ParentId=BaseId, PropArName = "بيرو", PropEnName = "Peru", Misc001 = "man/media/flags/peru.svg", Misc002 = "Peruvian", Misc003 = "PE", Misc004 = "بيروية" };
        public static VmInitialProperty Philippines => new() { PropId = (BaseId*1000)+150,ParentId=BaseId, PropArName = "الفلبين", PropEnName = "Philippines", Misc001 = "man/media/flags/philippines.svg", Misc002 = "Filipino", Misc003 = "PH", Misc004 = "فلبينية" };
        public static VmInitialProperty Poland => new() { PropId = (BaseId*1000)+151,ParentId=BaseId, PropArName = "بولندا", PropEnName = "Poland", Misc001 = "man/media/flags/poland.svg", Misc002 = "Polish", Misc003 = "PL", Misc004 = "بولندية" };
        public static VmInitialProperty Portugal => new() { PropId = (BaseId*1000)+152,ParentId=BaseId, PropArName = "البرتغال", PropEnName = "Portugal", Misc001 = "man/media/flags/portugal.svg", Misc002 = "Portuguese", Misc003 = "PT", Misc004 = "برتغالية" };
        public static VmInitialProperty PuertoRico => new() { PropId = (BaseId*1000)+153,ParentId=BaseId, PropArName = "بورتوريكو", PropEnName = "Puerto Rico", Misc001 = "man/media/flags/puerto-rico.svg", Misc002 = "Puerto Rican", Misc003 = "PR", Misc004 = "بورتوريكية" };
        public static VmInitialProperty Qatar => new() { PropId = (BaseId*1000)+154,ParentId=BaseId, PropArName = "قطر", PropEnName = "Qatar", Misc001 = "man/media/flags/qatar.svg", Misc002 = "Qatari", Misc003 = "QA", Misc004 = "قطرية" };
        public static VmInitialProperty Romania => new() { PropId = (BaseId*1000)+155,ParentId=BaseId, PropArName = "رومانيا", PropEnName = "Romania", Misc001 = "man/media/flags/romania.svg", Misc002 = "Romanian", Misc003 = "RO", Misc004 = "رومانية" };
        public static VmInitialProperty Russia => new() { PropId = (BaseId*1000)+156,ParentId=BaseId, PropArName = "روسيا", PropEnName = "Russian Federation", Misc001 = "man/media/flags/russia.svg", Misc002 = "Russian", Misc003 = "RU", Misc004 = "روسية" };
        public static VmInitialProperty Rwanda => new() { PropId = (BaseId*1000)+157,ParentId=BaseId, PropArName = "رواندا", PropEnName = "Rwanda", Misc001 = "man/media/flags/rwanda.svg", Misc002 = "Rwandan", Misc003 = "RW", Misc004 = "رواندية" };
        public static VmInitialProperty SaintBarthelemy => new() { PropId = (BaseId*1000)+158,ParentId=BaseId, PropArName = "سان بارتيلمي", PropEnName = "Saint Barthélemy", Misc001 = "man/media/flags/st-barts.svg", Misc002 = "Saint Barthélemois", Misc003 = "BL", Misc004 = "سان بارتيلموية" };
        public static VmInitialProperty SaintKittsAndNevis => new() { PropId = (BaseId*1000)+159,ParentId=BaseId, PropArName = "سانت كيتس ونيفيس", PropEnName = "Saint Kitts and Nevis", Misc001 = "man/media/flags/saint-kitts-and-nevis.svg", Misc002 = "Kittitian/Nevisian", Misc003 = "KN", Misc004 = "سانت كيتسية/نيفيسية" };
        public static VmInitialProperty SaintLucia => new() { PropId = (BaseId*1000)+160,ParentId=BaseId, PropArName = "سانت لوسيا", PropEnName = "Saint Lucia", Misc001 = "man/media/flags/st-lucia.svg", Misc002 = "Saint Lucian", Misc003 = "LC", Misc004 = "سانت لوسية" };
        public static VmInitialProperty SaintMartin => new() { PropId = (BaseId*1000)+161,ParentId=BaseId, PropArName = "سانت مارتين", PropEnName = "Saint Martin (French part)", Misc001 = "man/media/flags/sint-maarten.svg", Misc002 = "Saint-Martinois", Misc003 = "MF", Misc004 = "سانت مارتينية" };
        public static VmInitialProperty SaintVincentAndTheGrenadines => new() { PropId = (BaseId*1000)+162,ParentId=BaseId, PropArName = "سانت فينسنت والغرينادين", PropEnName = "Saint Vincent and the Grenadines", Misc001 = "man/media/flags/st-vincent-and-the-grenadines.svg", Misc002 = "Vincentian", Misc003 = "VC", Misc004 = "سانت فينسنتية" };
        public static VmInitialProperty Samoa => new() { PropId = (BaseId*1000)+163,ParentId=BaseId, PropArName = "ساموا", PropEnName = "Samoa", Misc001 = "man/media/flags/samoa.svg", Misc002 = "Samoan", Misc003 = "WS", Misc004 = "ساموية" };
        public static VmInitialProperty SanMarino => new() { PropId = (BaseId*1000)+164,ParentId=BaseId, PropArName = "سان مارينو", PropEnName = "San Marino", Misc001 = "man/media/flags/san-marino.svg", Misc002 = "Sammarinese", Misc003 = "SM", Misc004 = "سان مارينية" };
        public static VmInitialProperty SaoTomeAndPrincipe => new() { PropId = (BaseId*1000)+165,ParentId=BaseId, PropArName = "ساو تومي وبرينسيبي", PropEnName = "Sao Tome and Principe", Misc001 = "man/media/flags/sao-tome-and-prince.svg", Misc002 = "Sao Tomean", Misc003 = "ST", Misc004 = "ساو تومية" };
        public static VmInitialProperty SaudiArabia => new() { PropId = (BaseId*1000)+166,ParentId=BaseId, PropArName = "المملكة العربية السعودية", PropEnName = "Saudi Arabia", Misc001 = "man/media/flags/saudi-arabia.svg", Misc002 = "Saudi Arabian", Misc003 = "SA", Misc004 = "سعودية" };
        public static VmInitialProperty Senegal => new() { PropId = (BaseId*1000)+167,ParentId=BaseId, PropArName = "السنغال", PropEnName = "Senegal", Misc001 = "man/media/flags/senegal.svg", Misc002 = "Senegalese", Misc003 = "SN", Misc004 = "سنغالية" };
        public static VmInitialProperty Serbia => new() { PropId = (BaseId*1000)+168,ParentId=BaseId, PropArName = "صربيا", PropEnName = "Serbia", Misc001 = "man/media/flags/serbia.svg", Misc002 = "Serbian", Misc003 = "RS", Misc004 = "صربية" };
        public static VmInitialProperty Seychelles => new() { PropId = (BaseId*1000)+169,ParentId=BaseId, PropArName = "سيشل", PropEnName = "Seychelles", Misc001 = "man/media/flags/seychelles.svg", Misc002 = "Seychellois", Misc003 = "SC", Misc004 = "سيشلية" };
        public static VmInitialProperty SierraLeone => new() { PropId = (BaseId*1000)+170,ParentId=BaseId, PropArName = "سيراليون", PropEnName = "Sierra Leone", Misc001 = "man/media/flags/sierra-leone.svg", Misc002 = "Sierra Leonean", Misc003 = "SL", Misc004 = "سيراليونية" };
        public static VmInitialProperty Singapore => new() { PropId = (BaseId*1000)+171,ParentId=BaseId, PropArName = "سنغافورة", PropEnName = "Singapore", Misc001 = "man/media/flags/singapore.svg", Misc002 = "Singaporean", Misc003 = "SG", Misc004 = "سنغافورية" };
        public static VmInitialProperty SintMaarten => new() { PropId = (BaseId*1000)+172,ParentId=BaseId, PropArName = "سينت مارتن", PropEnName = "Sint Maarten (Dutch part)", Misc001 = "man/media/flags/sint-maarten.svg", Misc002 = "Sint Maartener", Misc003 = "SX", Misc004 = "سينت مارتينية" };
        public static VmInitialProperty Slovakia => new() { PropId = (BaseId*1000)+173,ParentId=BaseId, PropArName = "سلوفاكيا", PropEnName = "Slovakia", Misc001 = "man/media/flags/slovakia.svg", Misc002 = "Slovak", Misc003 = "SK", Misc004 = "سلوفاكية" };
        public static VmInitialProperty Slovenia => new() { PropId = (BaseId*1000)+174,ParentId=BaseId, PropArName = "سلوفينيا", PropEnName = "Slovenia", Misc001 = "man/media/flags/slovenia.svg", Misc002 = "Slovenian", Misc003 = "SI", Misc004 = "سلوفينية" };
        public static VmInitialProperty SolomonIslands => new() { PropId = (BaseId*1000)+175,ParentId=BaseId, PropArName = "جزر سليمان", PropEnName = "Solomon Islands", Misc001 = "man/media/flags/solomon-islands.svg", Misc002 = "Solomon Islander", Misc003 = "SB", Misc004 = "سليمانية" };
        public static VmInitialProperty Somalia => new() { PropId = (BaseId*1000)+176,ParentId=BaseId, PropArName = "الصومال", PropEnName = "Somalia", Misc001 = "man/media/flags/somalia.svg", Misc002 = "Somali", Misc003 = "SO", Misc004 = "صومالية" };
        public static VmInitialProperty SouthAfrica => new() { PropId = (BaseId*1000)+177,ParentId=BaseId, PropArName = "جنوب أفريقيا", PropEnName = "South Africa", Misc001 = "man/media/flags/south-africa.svg", Misc002 = "South African", Misc003 = "ZA", Misc004 = "جنوب أفريقية" };
        public static VmInitialProperty SouthKorea => new() { PropId = (BaseId*1000)+178,ParentId=BaseId, PropArName = "كوريا الجنوبية", PropEnName = "South Korea", Misc001 = "man/media/flags/south-korea.svg", Misc002 = "South Korean", Misc003 = "KR", Misc004 = "كورية جنوبية" };
        public static VmInitialProperty SouthSudan => new() { PropId = (BaseId*1000)+179,ParentId=BaseId, PropArName = "جنوب السودان", PropEnName = "South Sudan", Misc001 = "man/media/flags/south-sudan.svg", Misc002 = "South Sudanese", Misc003 = "SS", Misc004 = "جنوب سودانية" };
        public static VmInitialProperty Spain => new() { PropId = (BaseId*1000)+180,ParentId=BaseId, PropArName = "إسبانيا", PropEnName = "Spain", Misc001 = "man/media/flags/spain.svg", Misc002 = "Spanish", Misc003 = "ES", Misc004 = "إسبانية" };
        public static VmInitialProperty SriLanka => new() { PropId = (BaseId*1000)+181,ParentId=BaseId, PropArName = "سريلانكا", PropEnName = "Sri Lanka", Misc001 = "man/media/flags/sri-lanka.svg", Misc002 = "Sri Lankan", Misc003 = "LK", Misc004 = "سريلانكية" };
        public static VmInitialProperty Sudan => new() { PropId = (BaseId*1000)+182,ParentId=BaseId, PropArName = "السودان", PropEnName = "Sudan", Misc001 = "man/media/flags/sudan.svg", Misc002 = "Sudanese", Misc003 = "SD", Misc004 = "سودانية" };
        public static VmInitialProperty Suriname => new() { PropId = (BaseId*1000)+183,ParentId=BaseId, PropArName = "سورينام", PropEnName = "Suriname", Misc001 = "man/media/flags/suriname.svg", Misc002 = "Surinamese", Misc003 = "SR", Misc004 = "سورينامية" };
        public static VmInitialProperty Swaziland => new() { PropId = (BaseId*1000)+184,ParentId=BaseId, PropArName = "سوازيلاند", PropEnName = "Swaziland", Misc001 = "man/media/flags/swaziland.svg", Misc002 = "Swazi", Misc003 = "SZ", Misc004 = "سوازية" };
        public static VmInitialProperty Sweden => new() { PropId = (BaseId*1000)+185,ParentId=BaseId, PropArName = "السويد", PropEnName = "Sweden", Misc001 = "man/media/flags/sweden.svg", Misc002 = "Swedish", Misc003 = "SE", Misc004 = "سويدية" };
        public static VmInitialProperty Switzerland => new() { PropId = (BaseId*1000)+186,ParentId=BaseId, PropArName = "سويسرا", PropEnName = "Switzerland", Misc001 = "man/media/flags/switzerland.svg", Misc002 = "Swiss", Misc003 = "CH", Misc004 = "سويسرية" };
        public static VmInitialProperty Syria => new() { PropId = (BaseId*1000)+187,ParentId=BaseId, PropArName = "سوريا", PropEnName = "Syrian Arab Republic", Misc001 = "man/media/flags/syria.svg", Misc002 = "Syrian", Misc003 = "SY", Misc004 = "سورية" };
        public static VmInitialProperty Taiwan => new() { PropId = (BaseId*1000)+188,ParentId=BaseId, PropArName = "تايوان", PropEnName = "Taiwan, Province of China", Misc001 = "man/media/flags/taiwan.svg", Misc002 = "Taiwanese", Misc003 = "TW", Misc004 = "تايوانية" };
        public static VmInitialProperty Tajikistan => new() { PropId = (BaseId*1000)+189,ParentId=BaseId, PropArName = "طاجيكستان", PropEnName = "Tajikistan", Misc001 = "man/media/flags/tajikistan.svg", Misc002 = "Tajikistani", Misc003 = "TJ", Misc004 = "طاجيكستانية" };
        public static VmInitialProperty Tanzania => new() { PropId = (BaseId*1000)+190,ParentId=BaseId, PropArName = "تنزانيا", PropEnName = "Tanzania, United Republic of", Misc001 = "man/media/flags/tanzania.svg", Misc002 = "Tanzanian", Misc003 = "TZ", Misc004 = "تنزانية" };
        public static VmInitialProperty Thailand => new() { PropId = (BaseId*1000)+191,ParentId=BaseId, PropArName = "تايلاند", PropEnName = "Thailand", Misc001 = "man/media/flags/thailand.svg", Misc002 = "Thai", Misc003 = "TH", Misc004 = "تايلندية" };
        public static VmInitialProperty Togo => new() { PropId = (BaseId*1000)+192,ParentId=BaseId, PropArName = "توغو", PropEnName = "Togo", Misc001 = "man/media/flags/togo.svg", Misc002 = "Togolese", Misc003 = "TG", Misc004 = "توغولية" };
        public static VmInitialProperty Tokelau => new() { PropId = (BaseId*1000)+193,ParentId=BaseId, PropArName = "توكيلاو", PropEnName = "Tokelau", Misc001 = "man/media/flags/tokelau.svg", Misc002 = "Tokelauan", Misc003 = "TK", Misc004 = "توكيلاوية" };
        public static VmInitialProperty Tonga => new() { PropId = (BaseId*1000)+194,ParentId=BaseId, PropArName = "تونغا", PropEnName = "Tonga", Misc001 = "man/media/flags/tonga.svg", Misc002 = "Tongan", Misc003 = "TO", Misc004 = "تونغية" };
        public static VmInitialProperty TrinidadAndTobago => new() { PropId = (BaseId*1000)+195,ParentId=BaseId, PropArName = "ترينيداد وتوباغو", PropEnName = "Trinidad and Tobago", Misc001 = "man/media/flags/trinidad-and-tobago.svg", Misc002 = "Trinidadian/Tobagonian", Misc003 = "TT", Misc004 = "ترينيدادية" };
        public static VmInitialProperty Tunisia => new() { PropId = (BaseId*1000)+196,ParentId=BaseId, PropArName = "تونس", PropEnName = "Tunisia", Misc001 = "man/media/flags/tunisia.svg", Misc002 = "Tunisian", Misc003 = "TN", Misc004 = "تونسية" };
        public static VmInitialProperty Turkey => new() { PropId = (BaseId*1000)+197,ParentId=BaseId, PropArName = "تركيا", PropEnName = "Turkey", Misc001 = "man/media/flags/turkey.svg", Misc002 = "Turkish", Misc003 = "TR", Misc004 = "تركية" };
        public static VmInitialProperty Turkmenistan => new() { PropId = (BaseId*1000)+198,ParentId=BaseId, PropArName = "تركمانستان", PropEnName = "Turkmenistan", Misc001 = "man/media/flags/turkmenistan.svg", Misc002 = "Turkmen", Misc003 = "TM", Misc004 = "تركمانستانية" };
        public static VmInitialProperty TurksAndCaicosIslands => new() { PropId = (BaseId*1000)+199,ParentId=BaseId, PropArName = "جزر توركس وكايكوس", PropEnName = "Turks and Caicos Islands", Misc001 = "man/media/flags/turks-and-caicos.svg", Misc002 = "Turks and Caicos Islander", Misc003 = "TC", Misc004 = "توركسية وكايكوسية" };
        public static VmInitialProperty Tuvalu => new() { PropId = (BaseId*1000)+200,ParentId=BaseId, PropArName = "توفالو", PropEnName = "Tuvalu", Misc001 = "man/media/flags/tuvalu.svg", Misc002 = "Tuvaluan", Misc003 = "TV", Misc004 = "توفالوية" };
        public static VmInitialProperty Uganda => new() { PropId = (BaseId*1000)+201,ParentId=BaseId, PropArName = "أوغندا", PropEnName = "Uganda", Misc001 = "man/media/flags/uganda.svg", Misc002 = "Ugandan", Misc003 = "UG", Misc004 = "أوغندية" };
        public static VmInitialProperty Ukraine => new() { PropId = (BaseId*1000)+202,ParentId=BaseId, PropArName = "أوكرانيا", PropEnName = "Ukraine", Misc001 = "man/media/flags/ukraine.svg", Misc002 = "Ukrainian", Misc003 = "UA", Misc004 = "أوكرانية" };
        public static VmInitialProperty UnitedArabEmirates => new() { PropId = (BaseId*1000)+203,ParentId=BaseId, PropArName = "الإمارات العربية المتحدة", PropEnName = "United Arab Emirates", Misc001 = "man/media/flags/united-arab-emirates.svg", Misc002 = "Emirati", Misc003 = "AE", Misc004 = "إماراتية" };
        public static VmInitialProperty UnitedKingdom => new() { PropId = (BaseId*1000)+204,ParentId=BaseId, PropArName = "المملكة المتحدة", PropEnName = "United Kingdom", Misc001 = "man/media/flags/united-kingdom.svg", Misc002 = "British", Misc003 = "GB", Misc004 = "بريطانية" };
        public static VmInitialProperty UnitedStates => new() { PropId = (BaseId*1000)+205,ParentId=BaseId, PropArName = "الولايات المتحدة", PropEnName = "United States", Misc001 = "man/media/flags/united-states.svg", Misc002 = "American", Misc003 = "US", Misc004 = "أمريكية" };
        public static VmInitialProperty Uruguay => new() { PropId = (BaseId*1000)+206,ParentId=BaseId, PropArName = "أورغواي", PropEnName = "Uruguay", Misc001 = "man/media/flags/uruguay.svg", Misc002 = "Uruguayan", Misc003 = "UY", Misc004 = "أورغوانية" };
        public static VmInitialProperty Uzbekistan => new() { PropId = (BaseId*1000)+207,ParentId=BaseId, PropArName = "أوزبكستان", PropEnName = "Uzbekistan", Misc001 = "man/media/flags/uzbekistan.svg", Misc002 = "Uzbekistani", Misc003 = "UZ", Misc004 = "أوزبكستانية" };
        public static VmInitialProperty Vanuatu => new() { PropId = (BaseId*1000)+208,ParentId=BaseId, PropArName = "فانواتو", PropEnName = "Vanuatu", Misc001 = "man/media/flags/vanuatu.svg", Misc002 = "Ni-Vanuatu", Misc003 = "VU", Misc004 = "فانواتية" };
        public static VmInitialProperty Venezuela => new() { PropId = (BaseId*1000)+209,ParentId=BaseId, PropArName = "فنزويلا", PropEnName = "Venezuela, Bolivarian Republic of", Misc001 = "man/media/flags/venezuela.svg", Misc002 = "Venezuelan", Misc003 = "VE", Misc004 = "فنزويلية" };
        public static VmInitialProperty Vietnam => new() { PropId = (BaseId*1000)+210,ParentId=BaseId, PropArName = "فيتنام", PropEnName = "Vietnam", Misc001 = "man/media/flags/vietnam.svg", Misc002 = "Vietnamese", Misc003 = "VN", Misc004 = "فيتنامية" };
        public static VmInitialProperty VirginIslands => new() { PropId = (BaseId*1000)+211,ParentId=BaseId, PropArName = "جزر فيرجن", PropEnName = "Virgin Islands", Misc001 = "man/media/flags/virgin-islands.svg", Misc002 = "Virgin Islander", Misc003 = "VI", Misc004 = "فيرجنية" };
        public static VmInitialProperty Yemen => new() { PropId = (BaseId*1000)+212,ParentId=BaseId, PropArName = "اليمن", PropEnName = "Yemen", Misc001 = "man/media/flags/yemen.svg", Misc002 = "Yemeni", Misc003 = "YE", Misc004 = "يمنية" };
        public static VmInitialProperty Zambia => new() { PropId = (BaseId*1000)+213,ParentId=BaseId, PropArName = "زامبيا", PropEnName = "Zambia", Misc001 = "man/media/flags/zambia.svg", Misc002 = "Zambian", Misc003 = "ZM", Misc004 = "زامبية" };
        public static VmInitialProperty Zimbabwe => new() { PropId = (BaseId*1000)+214,ParentId=BaseId, PropArName = "زيمبابوي", PropEnName = "Zimbabwe", Misc001 = "man/media/flags/zimbabwe.svg", Misc002 = "Zimbabwean", Misc003 = "ZW", Misc004 = "زيمبابوية" };
        public static VmInitialProperty Micronesia => new() { PropId = (BaseId*1000)+215,ParentId=BaseId, PropArName = "ميكرونيزيا", PropEnName = "Micronesia, Federated States of", Misc001 = "man/media/flags/micronesia.svg", Misc002 = "Micronesian", Misc003 = "FM", Misc004 = "ميكرونيزية" };
        public static VmInitialProperty Moldova => new() { PropId = (BaseId*1000)+216,ParentId=BaseId, PropArName = "مولدوفا", PropEnName = "Moldova, Republic of", Misc001 = "man/media/flags/moldova.svg", Misc002 = "Moldovan", Misc003 = "MD", Misc004 = "مولدوفية" };
        public static VmInitialProperty Monaco => new() { PropId = (BaseId*1000)+217,ParentId=BaseId, PropArName = "موناكو", PropEnName = "Monaco", Misc001 = "man/media/flags/monaco.svg", Misc002 = "Monegasque", Misc003 = "MC", Misc004 = "موناكية" };
        public static VmInitialProperty Mongolia => new() { PropId = (BaseId*1000)+218,ParentId=BaseId, PropArName = "منغوليا", PropEnName = "Mongolia", Misc001 = "man/media/flags/mongolia.svg", Misc002 = "Mongolian", Misc003 = "MN", Misc004 = "منغولية" };
        public static VmInitialProperty Montenegro => new() { PropId = (BaseId*1000)+219,ParentId=BaseId, PropArName = "الجبل الأسود", PropEnName = "Montenegro", Misc001 = "man/media/flags/montenegro.svg", Misc002 = "Montenegrin", Misc003 = "ME", Misc004 = "الجبل الأسود" };
        public static VmInitialProperty Montserrat => new() { PropId = (BaseId*1000)+220,ParentId=BaseId, PropArName = "مونتسرات", PropEnName = "Montserrat", Misc001 = "man/media/flags/montserrat.svg", Misc002 = "Montserratian", Misc003 = "MS", Misc004 = "مونتسراتية" };
        public static VmInitialProperty Morocco => new() { PropId = (BaseId*1000)+221,ParentId=BaseId, PropArName = "المغرب", PropEnName = "Morocco", Misc001 = "man/media/flags/morocco.svg", Misc002 = "Moroccan", Misc003 = "MA", Misc004 = "مغربية" };
        public static VmInitialProperty Mozambique => new() { PropId = (BaseId*1000)+222,ParentId=BaseId, PropArName = "موزمبيق", PropEnName = "Mozambique", Misc001 = "man/media/flags/mozambique.svg", Misc002 = "Mozambican", Misc003 = "MZ", Misc004 = "موزمبيقية" };
        public static VmInitialProperty Myanmar => new() { PropId = (BaseId*1000)+223,ParentId=BaseId, PropArName = "ميانمار", PropEnName = "Myanmar", Misc001 = "man/media/flags/myanmar.svg", Misc002 = "Burmese", Misc003 = "MM", Misc004 = "بورمية" };
    }
    public abstract class SeedActivities
{
    private static readonly long BaseId = SeedStatic.Activities.PropId;
    public static VmInitialActivity Adding { get; set; } = new() { PropId = (BaseId*100)+1,ParentId=BaseId, ActName = "Adding",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has added a new <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بإضافة <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity Update { get; set; } = new() { PropId = (BaseId*100)+2,ParentId=BaseId, ActName = "Updating",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has updated <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a> information",ArMessage="قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بتعديل بيانات <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity Delete { get; set; } = new() { PropId = (BaseId*100)+3,ParentId=BaseId, ActName = "Deleting",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has deleted <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بحذف <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity Join { get; set; } = new() { PropId = (BaseId*100)+4,ParentId=BaseId, ActName = "Joining",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has joined to <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بالانضمام إلى <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity Cancel { get; set; } = new() { PropId = (BaseId*100)+5,ParentId=BaseId, ActName = "Cancelling",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has cancelled <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بإلغاء <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity Block { get; set; } = new() { PropId = (BaseId*100)+6,ParentId=BaseId,  ActName = "Blocking",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has blocked <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> on <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="// قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بحظر a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> من <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity Due { get; set; } = new() { PropId = (BaseId*100)+7,ParentId=BaseId,  ActName = "Payment",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has paid KD {%DueAmount%} as due amount on <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="قام <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> بتسديد مبلغ وقدره {%DueAmount%} عن دوره في a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> من <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
    public static VmInitialActivity OverDue { get; set; } = new() { PropId = (BaseId*100)+9,ParentId=BaseId,  ActName = "OverDueAmount",EnMessage="<a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> has KD {%DueAmount%} as payment due on <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>",ArMessage="ترتب على <a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> دفعة مستحقة وقدرها {%DueAmount%} عن دوره في a role=\"button\" data-ore=\"customer/view/{%ActById%}\">{%ActByName%}</a> من <a role=\"button\" data-ore=\"{%ActOnRoute%}/view/{%ActOnId%}\">{%ActOnName%}</a>"};
}

public class SeedEntryContentTypes
{
    private static readonly long BaseId = SeedStatic.EntryContentTypes.PropId;
    public static VmInitialProperty Title => new() {PropId = (BaseId*100)+1,ParentId = BaseId,PropArName = "Title",PropEnName = "Title",Order = 1};
    public static VmInitialProperty SubTitle => new() {PropId = (BaseId*100)+2,ParentId = BaseId,PropArName = "SubTitle",PropEnName = "SubTitle",Order = 1};
    public static VmInitialProperty ShortDesc => new() {PropId = (BaseId*100)+3,ParentId = BaseId,PropArName = "Short-desc",PropEnName = "Short-desc",Order = 1};
    public static VmInitialProperty Content => new() {PropId = (BaseId*100)+4,ParentId = BaseId,PropArName = "Content",PropEnName = "Content",Order = 1};
    public static VmInitialProperty CardImage => new() {PropId = (BaseId*100)+5,ParentId = BaseId,PropArName = "Card Image",PropEnName = "Card Image",Order = 1};
    public static VmInitialProperty CoverImage => new() {PropId = (BaseId*100)+6,ParentId = BaseId,PropArName = "Cover Image",PropEnName = "Cover Image",Order = 1};
    public static VmInitialProperty BackgroundImage => new() {PropId = (BaseId*100)+7,ParentId = BaseId,PropArName = "Background Image",PropEnName = "Background Image",Order = 1};
    public static VmInitialProperty BackgroundVideo => new() {PropId = (BaseId*100)+8,ParentId = BaseId,PropArName = "Background Video",PropEnName = "Background Video",Order = 1};
    public static VmInitialProperty VectorImage => new() {PropId = (BaseId*100)+9,ParentId = BaseId,PropArName = "Vector Image",PropEnName = "Vector Image",Order = 1};
    public static VmInitialProperty RequiredImages => new() {PropId = (BaseId*100)+10,ParentId = BaseId,PropArName = "Required images",PropEnName = "Required images",Order = 1};
    public static VmInitialProperty RequiredVideos => new() {PropId = (BaseId*100)+11,ParentId = BaseId,PropArName = "Required Videos",PropEnName = "Required Videos",Order = 1};
    public static VmInitialProperty RequiredFiles => new() {PropId = (BaseId*100)+12,ParentId = BaseId,PropArName = "Required Files",PropEnName = "Required Files",Order = 1};
    public static VmInitialProperty ImageGalleries => new() {PropId = (BaseId*100)+13,ParentId = BaseId,PropArName = "Image Galleries",PropEnName = "Image Galleries",Order = 1};
    public static VmInitialProperty PlayLists => new() {PropId = (BaseId*100)+14,ParentId = BaseId,PropArName = "PlayLists",PropEnName = "Play Lists",Order = 1};
    public static VmInitialProperty HasListing => new() {PropId = (BaseId*100)+15,ParentId = BaseId,PropArName = "Has listing",PropEnName = "Has listing",Order = 1};
    public static VmInitialProperty HasInfo => new() {PropId = (BaseId*100)+16,ParentId = BaseId,PropArName = "Has info",PropEnName = "Has info",Order = 1};
    public static VmInitialProperty ImagesSlider => new() {PropId = (BaseId*100)+17,ParentId = BaseId,PropArName = "images slider",PropEnName = "images slider",Order = 1};
    public static VmInitialProperty Pv => new() {PropId = (BaseId*100)+19,ParentId = BaseId,PropArName = "images slider",PropEnName = "images slider",Order = 1};
}